# Generated by Django 5.1.6 on 2025-03-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Укажите название курса",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academy.course",
                verbose_name="Название курса",
            ),
        ),
    ]
