# Generated by Django 5.2b1 on 2025-03-16 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Укажите название курса",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="academy.course",
                verbose_name="Название курса",
            ),
        ),
    ]
