# Generated by Django 5.1.7 on 2025-03-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_subscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
