# Generated by Django 5.1.7 on 2025-04-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_delete_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
